filebeat.inputs:
  - type: docker
    combine_partial: true
    containers:
      path: "/var/lib/docker/containers"
      stream: all
      ids:
        - "*"

output.logstash:
  hosts: ["logstash:5044"]

# output.logstash:
#   hosts: ["127.0.0.1:5044"]
